apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: keycloak
spec:
  hosts:
    - keycloak.skycomposer.net
  gateways:
    - istio-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: keycloak.default.svc.cluster.local
            port:
              number: 80
          headers:
            request:
              set:
                x-forwarded-proto: https

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: whoami
spec:
  hosts:
    - keycloak.skycomposer.net
  gateways:
    - istio-gateway
  http:
    - match:
        - uri:
            prefix: /whoami
      route:
        - destination:
            host: whoami.default.svc.cluster.local
            port:
              number: 80
          headers:
            request:
              set:
                x-forwarded-proto: https

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: customermgmt
spec:
  hosts:
    - keycloak.skycomposer.net
  gateways:
    - istio-gateway
  http:
    - match:
        - uri:
            prefix: /customermgmt
      route:
        - destination:
            host: customermgmt.default.svc.cluster.local
            port:
              number: 80
          headers:
            request:
              set:
                x-forwarded-proto: https


---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: usermgmt
spec:
  hosts:
    - keycloak.skycomposer.net
  gateways:
    - istio-gateway
  http:
    - match:
        - uri:
            prefix: /usermgmt
      route:
        - destination:
            host: usermgmt.default.svc.cluster.local
            port:
              number: 80
          headers:
            request:
              set:
                x-forwarded-proto: https


---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana
spec:
  hosts:
    - keycloak.skycomposer.net
  gateways:
    - istio-gateway
  http:
    - match:
      - uri:
          prefix: /grafana
      route:
        - destination:
            host: grafana.istio-system.svc.cluster.local
            port:
              number: 3000            
          headers:
            request:
              set:
                x-forwarded-proto: https


---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali
spec:
  hosts:
    - keycloak.skycomposer.net
  gateways:
    - istio-gateway
  http:
    - match:
      - uri:
          prefix: /kiali
      route:
        - destination:
            host: kiali.istio-system.svc.cluster.local
            port:
              number: 20001            
          headers:
            request:
              set:
                x-forwarded-proto: https

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tracing
spec:
  hosts:
    - keycloak.skycomposer.net
  gateways:
    - istio-gateway
  http:
    - match:
      - uri:
          prefix: /jaeger
      route:
        - destination:
            host: tracing.istio-system.svc.cluster.local
            port:
              number: 80            
          headers:
            request:
              set:
                x-forwarded-proto: https

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: elasticsearch
spec:
  hosts:
    - keycloak.skycomposer.net
  gateways:
    - istio-gateway
  http:
    - match:
      - uri:
          prefix: /elasticsearch
      route:
        - destination:
            host: elasticsearch.logging.svc.cluster.local
            port:
              number: 9200            
          headers:
            request:
              set:
                x-forwarded-proto: https


---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kibana
spec:
  hosts:
    - keycloak.skycomposer.net
  gateways:
    - istio-gateway
  http:
    - match:
      - uri:
          prefix: /kibana
      route:
        - destination:
            host: kibana.logging.svc.cluster.local
            port:
              number: 5601            
          headers:
            request:
              set:
                x-forwarded-proto: https